spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true # 1부터 페이징 넘버를 설정하겠다.
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:eunblog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
  sql:
    init-model: always

hodolman:
  hello:
    name: "hodolman"
    home: "seoul"
    hobby: "programming"
    age: 36